[package]
name = "martian_engine"
version = "0.1.0"
authors = ["Nathan Koppel <nathankoppel0@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.7"
packed_simd = { version = "0.3.4", package = "packed_simd_2", features = ["into_bits"] }
